add test report to workflows

diff --git a/.github/workflows/notification-worker-lambdas.yml b/.github/workflows/notification-worker-lambdas.yml
--- a/.github/workflows/notification-worker-lambdas.yml
+++ b/.github/workflows/notification-worker-lambdas.yml
@@ -20,6 +20,7 @@ concurrency:
 permissions:
   id-token: write
   contents: read
+  checks: write
 
 jobs:
   build:
@@ -51,6 +52,16 @@ jobs:
 
       - name: Compile and test
         run: sbt "project notificationworkerlambda" "compile" "test"
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests
+          path: notificationworkerlambda/target/test-reports/TEST-*.xml
+          reporter: java-junit
+          only-summary: 'false'
+          fail-on-error: 'true'
 
       - name: Build docker image
         run: sbt docker:publishLocal
diff --git a/.github/workflows/report-extractor.yml b/.github/workflows/report-extractor.yml
--- a/.github/workflows/report-extractor.yml
+++ b/.github/workflows/report-extractor.yml
@@ -19,6 +19,7 @@ concurrency:
 permissions:
   id-token: write
   contents: read
+  checks: write
 
 jobs:
   build:
@@ -39,6 +40,16 @@ jobs:
 
       - name: Compile, test and assembly
         run: sbt "project reportextractor" "compile" "test" "assembly"
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests
+          path: reportextractor/target/test-reports/TEST-*.xml
+          reporter: java-junit
+          only-summary: 'false'
+          fail-on-error: 'true'
 
       - name: Copy jar to root
         run: cp reportextractor/target/scala-*/reportextractor.jar .
